<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUeorcr6\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUeorcr6/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUeorcr6.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUeorcr6\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUeorcr6\appProdProjectContainer([
    'container.build_hash' => 'Ueorcr6',
    'container.build_id' => 'f12aef7e',
    'container.build_time' => 1625909802,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUeorcr6');
